"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
run_mode = "concurrent"

[scripts.run.serve]
available_in = [ "local" ]
command = "make docs && make serve PORT=$CONDUCTOR_PORT"
default = true
icon = "globe"
